<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_View_lzd-search-common-icon ic-common-lis_d287ad</name>
   <tag></tag>
   <elementGuidId>512e998e-7872-4247-a65e-823bc754f85d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div/div/div/div/div/div[2]/div/div[4]/span[2]/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lzd-search-common-icon ic-common-list c3LmXO </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-spm-anchor-id</name>
      <type>Main</type>
      <value>a2a0e.searchlist.0.i3.15597463fdG8mu</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;c2P49E&quot;]/div[@class=&quot;ant-row c10-Cg&quot;]/div[@class=&quot;ant-col-24&quot;]/div[@class=&quot;ant-row&quot;]/div[@class=&quot;ant-col-20 ant-col-push-4 c1z9Ut&quot;]/div[@class=&quot;cUQuRr&quot;]/div[@class=&quot;c3wo-b&quot;]/div[@class=&quot;c3Cd9k&quot;]/div[@class=&quot;c2pQcz&quot;]/div[@class=&quot;c2tv0r&quot;]/span[2]/i[@class=&quot;lzd-search-common-icon ic-common-list c3LmXO&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div/div/div/div[2]/div/div[4]/span[2]/i</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/i</value>
   </webElementXpaths>
</WebElementEntity>
