<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Select_next-icon next-icon-arrow-down nex_03a595</name>
   <tag></tag>
   <elementGuidId>6ce43db5-f285-407d-acd6-2807387bf8d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gender > i.next-icon.next-icon-arrow-down.next-icon-medium.next-select-arrow</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='gender']/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>next-icon next-icon-arrow-down next-icon-medium next-select-arrow</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-spm-anchor-id</name>
      <type>Main</type>
      <value>a2a0e.edit_profile.1.i3.6c3f19878JBkn5</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gender&quot;)/i[@class=&quot;next-icon next-icon-arrow-down next-icon-medium next-select-arrow&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='gender']/i</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/span/i</value>
   </webElementXpaths>
</WebElementEntity>
